language: python
python:
  - "3.5"
sudo: false
cache: pip
addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
env:
  global:
  - VERSION="12.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"
  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="OCA/OCB" MAKEPOT="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coverage
  - pip install coveralls
script:
  - coverage run -m unittest discover -s . -p '*_unit_test.py'
after_success:
  - coveralls
